name: bun-hono-expense-tracker
services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - expense-tracker-docker-pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  expense-tracker-docker-pg-data:
